services:
  api-gateway:
    image: nginx:latest
    container_name: sns-api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sns-network
    restart: unless-stopped

networks:
  sns-network:
    name: sns-network
    driver: bridge